---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 752535759555555329-M8LcaPPiK6HvqU6PJC0HPtVPc7KRp5U
:access_token_secret: j4CSU0o0OPxqkuprloUiQMJzMRhfbA2tI9bXizRP6rFJD
